version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: 0.0.0.0:${APP_HTTP_PORT:-8081}
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  poll:
    debug: ${RR_DEBUG:-false}
    num_workers: ${RR_NUM_WORKERS:-8}
    max_jobs: ${RR_MAX_JOBS:-16}
    max_worker_memory: ${RR_MAX_WORKER_MEMORY:-512}

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

logs:
  mode: development
  level: debug
  channels:
    http:
      mode: production
      level: panic
      encoding: console
      output: stdout
      err_output: stderr
    server:
      mode: production
      level: info
      encoding: json
      output: stdout
      err_output: stdout
    rpc:
      mode: raw
      level: debug
      encoding: console
      output: stderr
      err_output: stdout
